export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILED = 'PURCHASE_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS = 'FETCH_ORDERS';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_AUTO_LOGOUT = 'AUTH_AUTO_LOGOUT';
export const LOGOUT = 'LOGOUT';

export const SET_AUTO_REDIRECT_PATH = 'SET_AUTO_REDIRECT_PATH';